name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl

      - name: Build
        run: export CGO_ENABLED=0 && go build -v ./...

      - name: Test
        run: go test -cover -v ./...
